### ISSUE TITLE
Do you know of a way of capturing events.

### ISSUE THREAD

**Issue by willoughby** [GiGurra/dcs-remote2#1]
Im looking to use your api to capture events on our traning server. Would you have an example?

**Comment by GiGurra** [comment]
Not quite sure I understand what you're trying to do.. 
Do you mean to export data from some lua envionment?
DCS Remote comes preconfigured to handle communication to/from the export environment, but should work from any environment, provided you adapt the hooks and have some update function you can attach to running every simulation cycle.

After that it's just like the examples on the github README right here.
